use crate::image::Image;
use photon_rs::noise;
use pyo3::prelude::*;

#[pymethods]
impl Image {
    /// Add randomized noise to an image. This function adds a Gaussian Noise Sample to each pixel through incrementing each channel by a randomized offset. This randomized offset is generated by creating a randomized thread pool.
    ///
    /// Examples
    /// --------
    ///
    /// .. code-block:: python3
    ///
    ///     img.add_noise_rand()
    ///
    fn add_noise_rand(&mut self) -> PyResult<()> {
        let pimg = &self.img;
        let photon_img =
            photon_rs::PhotonImage::new(pimg.get_raw_pixels(), pimg.get_width(), pimg.get_height());
        let img = noise::add_noise_rand(photon_img);
        self.img = img;
        Ok(())
    }

    /// Add pink-tinted noise to an image.
    ///
    /// Examples
    /// --------
    ///
    /// .. code-block:: python3
    ///
    ///     img.add_noise_rand()
    ///
    fn pink_noise(&mut self) -> PyResult<()> {
        noise::pink_noise(&mut self.img);
        Ok(())
    }
}
